### ISSUE TITLE
Directory Viewer doesn't work well with symlinked directories

### ISSUE THREAD

**Issue by iversond** [cy2hq/PeopleSoft-Directory-Viewer#22]
**Describe the bug**
On our app server, we use symlinks from our NFS mount to put our PS_CUST_HOME in a directory with our PeopleSoft files. E.g.  `/mnt/share/peoplesoft/cust/hrdev` is symlinked to `/u01/app/psoft/cust/hrdev` 

When we use the path `/u01/app/psoft/cust/hrdev` in the Directory Viewer Setup pages, we cannot Upload files into a directory. During troubleshooting, the value of `&fileOrChildDirPathAndName` returns the absolute path, not the symlinked path.

**To Reproduce**
1. Create a symlink for a directory

    ```bash
    cd /u01/app/psoft
    ln -s /tmp /u01/app/psoft/tmp
    mkdir -p /u01/app/psoft/tmp/files/upload
    ```

2. In the Directory Setup page, add `/u01/app/psoft/tmp/files` and make `/u01/app/psoft/tmp/files/upload` as the Upload directory.
3. In the Directory Viewer page, attempt to upload a file the to `upload` folder.
4. "Upload File" is not listed in the Actions menu.

**Expected behavior**
The Directory Viewer should accept the symlinked path, not the absolute path

**Additional context**
The short-term fix is to use the absolute paths in the Directory Setup pages.

**Comment by ernstlahaye** [comment]
Thanks Dan.

Solution direction: 
Installation value to indicate if symlinks need to be used yes / no. If Yes, we use the symlink value for a folder if it exists and compare that to the values we set in the setup page.

**Comment by ernstlahaye** [comment]
Hi Dan, 

Finally solved the issue, in the end it was simple .... of course... we now use the .getpath() function instead of the getCanonicalPath() in the directoryviewer class and till now at least, all seems to work as expected and I have not seen any downside to changing. Feel free to change and test in your environments if you have a moment. It works fine for me in 8.59.

New version of the viewer will be online really soon now. 

Kind regards,
Ernst
